### ISSUE TITLE
h5_scannet

### ISSUE THREAD

**Issue by zhangbilang** [verlab/DescriptorReasoning_ACCV_2024#1]
Hello, since the ScanNet dataset is 1.2T in size, it's rather difficult to directly download and create h5_scannet. Could you please provide the download link for your h5_scannet? We would be extremely grateful.

**Comment by felipecadar** [comment]
Hi @SmudgedWings, thank you for the interest in our work.

The final dataset is ~300 GB, and unfortunately I do not have a place to host it. I hope this changes in the future, but for now I can only provide help generating it from the original data.

**Comment by galahies** [comment]
> 您好，由于ScanNet数据集有1.2T大小，直接下载并创建h5_scannet比较困难。您能否提供一下您的h5_scannet的下载链接？我们将不胜感激。

您好，请问您有解决数据集的问题吗，下载数据集确实很麻烦

**Comment by zhangbilang** [comment]
> > 您好，由于ScanNet数据集有1.2T大小，直接下载并创建h5_scannet比较困难。您能否提供一下您的h5_scannet的下载链接？我们将不胜感激。
> 
> 您好，请问您有解决数据集的问题吗，下载数据集确实很麻烦

按照我的理解，数据集仅仅需要scannet中每个sense的.sens文件，例如datasets/scannet/scans/scene0070_00/scene0070_00.sens 对于训练，你可以仅仅下载这些文件。对于调试，你可以仅仅下载单个sense的.sens文件。你可以验证并尝试我这个想法

**Comment by felipecadar** [comment]
Hey @SmudgedWings and @galahies 
I took some time to upload my dataset to a personal OneDrive. It may not be there for a long time, but it should help until I find a more permanent solution. It is 165GB compressed and ~300GB after extracting.

You can use this link to download it with a browser 

[h5_scannet.zip](https://1drv.ms/u/s!ApoKu6UBov7DhJFqYitDRECpry6zEA?download=1)

Or run this command in the terminal 

```bash
wget https://io1bgw.by.files.1drv.com/y4mNHmz8PVahDwed0b8-78UD82YVJ90U1eWPVFnIL6eTmj7cL43FkG4sEE0hm257tSLD1EPNBO1mw7ucu4pSzNq8JsSepVZanhfczlAqA5WvhUrkD9Qe17cLAEbFcROKxUsGpOwuT-dP4yzzFQw8_tNDwRKRjhwGSN0uGZgHMh8ilyv9bsmqWEWBk-dCoA6CGfc_2dzXksBjHI8mY1Kyx52Ps_bKgHWB1aCureKeWZCuJ8\?AVOverride\=1 -O h5_scannet.zip
```

**Comment by galahies** [comment]
> 嘿@SmudgedWings和@galahies 我花了一些时间将我的数据集上传到个人 OneDrive。它可能不会在那里待很长时间，但在我找到更持久的解决方案之前它应该会有所帮助。压缩后为 165GB，解压后约为 300GB。
> 
> 您可以使用此链接通过浏览器下载
> 
> [h5_扫描网络.zip](https://1drv.ms/u/s!ApoKu6UBov7DhJFqYitDRECpry6zEA?download=1)
> 
> 或者在终端中运行此命令
> 
> ```shell
> wget https://io1bgw.by.files.1drv.com/y4mNHmz8PVahDwed0b8-78UD82YVJ90U1eWPVFnIL6eTmj7cL43FkG4sEE0hm257tSLD1EPNBO1mw7ucu4pSzNq8JsSepVZanhfczlAqA5WvhUrkD9Qe17cLAEbFcROKxUsGpOwuT-dP4yzzFQw8_tNDwRKRjhwGSN0uGZgHMh8ilyv9bsmqWEWBk-dCoA6CGfc_2dzXksBjHI8mY1Kyx52Ps_bKgHWB1aCureKeWZCuJ8\?AVOverride\=1 -O h5_scannet.zip
> ```
Thank you for your open source spirit. You have solved a large part of my troubles, which is great and beyond words

**Comment by Martin-GD** [comment]
> Hey @SmudgedWings and @galahies I took some time to upload my dataset to a personal OneDrive. It may not be there for a long time, but it should help until I find a more permanent solution. It is 165GB compressed and ~300GB after extracting.
> 
> You can use this link to download it with a browser
> 
> [h5_scannet.zip](https://1drv.ms/u/s!ApoKu6UBov7DhJFqYitDRECpry6zEA?download=1)
> 
> Or run this command in the terminal
> 
> ```shell
> wget https://io1bgw.by.files.1drv.com/y4mNHmz8PVahDwed0b8-78UD82YVJ90U1eWPVFnIL6eTmj7cL43FkG4sEE0hm257tSLD1EPNBO1mw7ucu4pSzNq8JsSepVZanhfczlAqA5WvhUrkD9Qe17cLAEbFcROKxUsGpOwuT-dP4yzzFQw8_tNDwRKRjhwGSN0uGZgHMh8ilyv9bsmqWEWBk-dCoA6CGfc_2dzXksBjHI8mY1Kyx52Ps_bKgHWB1aCureKeWZCuJ8\?AVOverride\=1 -O h5_scannet.zip
> ```

Sorry to bother you, the link to h5scannet.rip is invalid. Could you please provide a valid link again? Thank you very much!

**Comment by felipecadar** [comment]
Hi there @Martin-GD.
This link is expired because it was a temporary signed link to be used with wget. Since it expires too fast, I'm providing the correct on (not compatible with wget) in the project readme. If you want to use it with the command line please use some of the tutorials online ([like this one](https://askubuntu.com/questions/1205418/wget-or-curl-gives-403forbidden-while-downloading-file-from-onedrive-for-busine)) to sign it.

Here it is for reference [h5_scannet.zip](https://1drv.ms/u/s!ApoKu6UBov7DhJFqKHP_5o72YhOLtA?e=8T79oi)
