### ISSUE TITLE
about h5_scannet.zip

### ISSUE THREAD

**Issue by galahies** [verlab/DescriptorReasoning_ACCV_2024#3]
The link you stored has expired. When I downloaded to 90GB, will there be any new additions in the future

**Comment by felipecadar** [comment]
It's a little difficult to share it in a way you can download it via the command line, but you can just click the sharing link and open a browser window to download it.

[h5_scannet.zip](https://1drv.ms/u/s!ApoKu6UBov7DhJFqKHP_5o72YhOLtA?e=8T79oi)
