### ISSUE TITLE
a small issue in the code (mutilGPU training)

### ISSUE THREAD

**Issue by zhangbilang** [verlab/DescriptorReasoning_ACCV_2024#4]
Hello, the current code has reached the training stage, but there seems to be some issue in the code that is preventing the training from running properly. Could you please carefully verify it? It seems to be a small issue in the code.

**Comment by zhangbilang** [comment]
class ReasoningBase(torch.nn.Module):
      self.conf.dustbin # self.conf  missing key "dustbin"
I added "dustbin" and set it to False, and the training works fine. However, I want to know what it represents. Should it be set to True or False for training?

**Comment by felipecadar** [comment]
Sorry about that. This variable was used in small test we did and should have been removed. If you added it as false, it is consistent with the paper results. I'll update the code to remove it.

**Comment by felipecadar** [comment]
Done :) 
Thanks
